<a href="https://colab.research.google.com/github/Anthony18xd/numpy/blob/main/ejercicios_bacicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numPY LIBRERIA DE CIENCIA DE DATOS**

In [2]:
import numpy as np
#pip intall numpy

In [3]:
array_id=np.array((10,20,30))
print(array_id)

[10 20 30]


In [4]:
array_id

array([10, 20, 30])

In [5]:
array_2d=np.array(((10,20,30),(50,60,70)))
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

In [8]:
array_3d=np.array((((10.5,20,30,40),(60,70,80,90),(5,7,9,8))),dtype=float)
array_3d

array([[10.5, 20. , 30. , 40. ],
       [60. , 70. , 80. , 90. ],
       [ 5. ,  7. ,  9. ,  8. ]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array de unos con 2 dimensiones 4 filas 5 columnas

In [12]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

arrays intervalos y saltos

In [13]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [15]:
import numpy as np

def es_primo(n):
    if n < 2:
        return False
    return not any(n % i == 0 for i in range(2, int(n**0.5) + 1))

numeros = np.arange(15, 30)
primos = numeros[np.array([es_primo(num) for num in numeros])]
print(primos)

[17 19 23 29]


array con intervalos y divisiones

In [16]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

arrays con valores dados

In [18]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

array matriz identidad y diagonal de unos

In [23]:
np.eye((3),(0))

array([], shape=(3, 0), dtype=float64)

array valos aleatorios

In [28]:
np.random.random((4,4))

array([[0.31277018, 0.45551313, 0.75331627, 0.79093376],
       [0.36953182, 0.29002997, 0.74085523, 0.46843198],
       [0.99503574, 0.65530234, 0.41496882, 0.93844275],
       [0.67918789, 0.89891873, 0.71905967, 0.56082711]])

array de numeros vacios 4*3

In [31]:
np.empty((4,3))

array([[10.5, 20. , 30. ],
       [40. , 60. , 70. ],
       [80. , 90. ,  5. ],
       [ 7. ,  9. ,  8. ]])

guardar y cargar

In [48]:
#grabar
np.save('mi_array_3d.npy',array_3d)

In [50]:
#cargar
nl_array=np.load('mi_array_3d.npy')
nl_array

array([[10.5, 20. , 30. , 40. ],
       [60. , 70. , 80. , 90. ],
       [ 5. ,  7. ,  9. ,  8. ]])

In [52]:
array_2d=np.array(((10,20,30),(50,60,70)))
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

In [54]:
# cargar array_2d
loaded_array_2d = np.load('mi_array_2d.npy')
loaded_array_2d

array([[10, 20, 30],
       [50, 60, 70]])

grabar y cargar ficheros y texto

In [56]:
#grabar el fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [58]:
#cargar de fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])

EJERCICIOS PROPUESTOS

In [62]:
asignaturas = np.array(["Matemáticas", "Física", "Química", "Historia", "Lengua"])
print(asignaturas)

['Matemáticas' 'Física' 'Química' 'Historia' 'Lengua']


In [65]:
asignaturas = np.array(["Matemáticas", "Física", "Química", "Historia", "Lengua"])
for asignatura in asignaturas:
    f"Yo estudio {asignatura}"
    print(f"Yo estudio {asignatura}")

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


In [66]:
asignaturas = np.array(["Matemáticas", "Física", "Química", "Historia", "Lengua"])
notas = np.zeros(len(asignaturas))

for i, asignatura in enumerate(asignaturas):
    nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
    notas[i] = nota

resultados = [f"En {asignaturas[i]} has sacado {notas[i]}" for i in range(len(asignaturas))]
nota_media = np.mean(notas)

¿Qué nota has sacado en Matemáticas? 15
¿Qué nota has sacado en Física? 08
¿Qué nota has sacado en Química? 10
¿Qué nota has sacado en Historia? 16
¿Qué nota has sacado en Lengua? 18


In [67]:
numeros_loteria = np.zeros(6, dtype=int)

for i in range(6):
    numero = int(input(f"Introduce el número {i+1} ganador de la lotería primitiva: "))
    numeros_loteria[i] = numero

numeros_ordenados = np.sort(numeros_loteria)

Introduce el número 1 ganador de la lotería primitiva: 8
Introduce el número 2 ganador de la lotería primitiva: 45
Introduce el número 3 ganador de la lotería primitiva: 46
Introduce el número 4 ganador de la lotería primitiva: 78
Introduce el número 5 ganador de la lotería primitiva: 12
Introduce el número 6 ganador de la lotería primitiva: 16


In [71]:
numeros = np.arange(1, 11)
numeros_inverso = np.flip(numeros)
resultado_string = " , ".join(map(str, numeros_inverso))
print(resultado_string)

10 , 9 , 8 , 7 , 6 , 5 , 4 , 3 , 2 , 1


In [74]:
asignaturas = np.array(["Matemáticas", "Física", "Química", "Historia", "Lengua"])
notas = np.zeros(len(asignaturas))

for i, asignatura in enumerate(asignaturas):
    while True:
        try:
            nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
            if 0 <= nota <= 20:
                notas[i] = nota
                break
            else:
                print("Por favor, introduce una nota entre 0 y 20.")
        except ValueError:
            print("Entrada inválida. Por favor, introduce un número.")

suspensas_mask = notas <= 10  # Passing grade is 11, so 10 or below is failing
asignaturas_repetir = asignaturas[suspensas_mask]
notas_suspensas = notas[suspensas_mask]

print("\nAsignaturas a recuperar:")
if len(asignaturas_repetir) > 0:
    for i in range(len(asignaturas_repetir)):
        print(f"- {asignaturas_repetir[i]}: {notas_suspensas[i]}")
else:
    print("¡Enhorabuena! No tienes asignaturas a recuperar.")

¿Qué nota has sacado en Matemáticas? 01
¿Qué nota has sacado en Física? 15
¿Qué nota has sacado en Química? 16
¿Qué nota has sacado en Historia? 16
¿Qué nota has sacado en Lengua? 08

Asignaturas a recuperar:
- Matemáticas: 1.0
- Lengua: 8.0


In [79]:
import string
import numpy as np

abecedario = np.array(list(string.ascii_lowercase))
posiciones = np.arange(1, len(abecedario) + 1)
mask = posiciones % 3 != 0
abecedario_filtrado = abecedario[mask]
print(abecedario_filtrado)

['a' 'b' 'd' 'e' 'g' 'h' 'j' 'k' 'm' 'n' 'p' 'q' 's' 't' 'v' 'w' 'y' 'z']


In [80]:
palabra = input("Introduce una palabra: ").lower()
palabra_array = np.array(list(palabra))
palabra_invertida = np.flip(palabra_array)
es_palindromo = np.array_equal(palabra_array, palabra_invertida)

Introduce una palabra: hola


In [83]:
import numpy as np

palabra = input("Introduce una palabra: ").lower()
palabra_array = np.array(list(palabra))
vocales = np.array(['a', 'e', 'i', 'o', 'u'])

print(f"La palabra '{palabra}' contiene:")

for vocal in vocales:
    count = np.sum(palabra_array == vocal)
    print(f"- La vocal '{vocal}' aparece {count} veces.")

Introduce una palabra: hol
La palabra 'hol' contiene:
- La vocal 'a' aparece 0 veces.
- La vocal 'e' aparece 0 veces.
- La vocal 'i' aparece 0 veces.
- La vocal 'o' aparece 1 veces.
- La vocal 'u' aparece 0 veces.
